### ISSUE TITLE
Optimise build of cache

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/BALSAMIC#1055]
**Is your feature request related to a problem? Please describe.**
Today it takes quite some time to build the cache on new releases. If we want to have faster releases, and be able to do minor ones in with a faster turn-around, it would be god for the time of this to go down.

**Describe the solution you'd like**
- See what are the major bottlenecks in building the cache
- Find solutions to optimise build time
- Re-think if the entire cache needs to be built for every new update of BALSAMIC.

---

**Decisions (`2023-03-17` meeting)**:
- Use same cache for validation and deployment
- Avoid building the cache on each release. Further discussion needed on how to address it.

---

**This can be closed when:**
- [x] Balsamic version is unlinked from containers (#1220)
- [x] Same containers are used for validation/verification and deployment (#1221)
- [x] It's possible to download cache specifying the future release version (before bumping the Balsamic package version) (#1231)
- [x] It's possible to run analysis specifying the future release version (before bumping the Balsamic package version) https://github.com/Clinical-Genomics/BALSAMIC/pull/1244
- [x] Possibility to copy stage cache to production (start using relative paths for references) https://github.com/Clinical-Genomics/BALSAMIC/pull/1251
- [x] Update Atlas: https://github.com/Clinical-Genomics/atlas/pull/1926
