### ISSUE TITLE
Adding Sentieon UMI workflow to BALSAMIC

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#322]
**Is your feature request related to a problem? Please describe.**

**Background**: Circulating tumor DNA (ctDNA) sequencing is one of the techniques for detecting cancers. Although tumor-derived DNA contributes to a smaller part of the total blood cell-free DNA, the mutant allele frequency (MAF) of a variant detected from ctDNA sequencing data can be very low (as low as 0.1%). To detect such low-frequency variants, deep-sequencing is required. Further to minimize the sequencing errors and to adequately identify the sequencing reads from varying DNA fragments, during the library prep, each DNA fragment is ligated with unique molecular identifiers (UMIs) before the DNA amplification process. In the downstream bioinformatics analysis, prior to sequence read alignment, these UMI barcodes need to be properly extracted and removed.

**Tasks:**
- [x]  Write and test the snakemake workflow to run the UMI datasets 
- [x] Calling SNVs 
- [x] Calculate the allelic frequency and compare the effects across different dilution rates.
- [ ] Integrate the workflow into BALSAMIC 

**Describe the solution you'd like**

Sentieon provides utilities for UMI NGS data processing and variant calling. 

- _**Snakemake workflow design**_

- [x]  **_umi extract_** UMI tag extraction from unaligned input reads with adapter already removed
                             
- [x] **_umi consensus:_** Barcode-aware duplicate removal and consensus calling on aligned input

- [x] **_TNscope:_** Variant calling detection on the consensus reads

- [x] **_Density plots:_** Plot the distribution of tags before and after consensus calling

**Describe alternatives you've considered**

- [ ] Run the Sentieon tools umi extract with two modes (Singleton and Duplex) to evaluate the results of  variant detection. 

**Current BALSAMIC version**
`4.2.4`

**Comment by ashwini06** [comment]
This issue has moved to #359
