### ISSUE TITLE
BALSAMIC priorities and roadmap Q4 2020

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#410]
Long issue lists don't get done, and they are too focused to be defined as a project. Some issues are also part of other projects. This issue defines roadmap and priorities, with an aim for the next release. Hotfixes and emergency fixes are not included. If issues are missing, please create them.

## New features:
- [ ] Feat: Start analysis from VCF https://github.com/Clinical-Genomics/BALSAMIC/issues/408
- [ ] Feat: Start analysis from BAM/CRAM: https://github.com/Clinical-Genomics/BALSAMIC/issues/303
- [ ] Feat: WGS CRAM conversion: https://github.com/Clinical-Genomics/BALSAMIC/issues/303
- [x] Feat: QC model for TGA, WES, and WGA: https://github.com/Clinical-Genomics/BALSAMIC/issues/394 Progress: https://github.com/Clinical-Genomics/BALSAMIC/pull/401
- [X] Refactor: Merge workflows into one: https://github.com/Clinical-Genomics/BALSAMIC/issues/412 Done in https://github.com/Clinical-Genomics/BALSAMIC/pull/428
- [ ] Feat: Update GATK4: https://github.com/Clinical-Genomics/BALSAMIC/issues/278
- [X] Feat: Filter for tumor-normal https://github.com/Clinical-Genomics/BALSAMIC/issues/435 done in PR https://github.com/Clinical-Genomics/BALSAMIC/pull/441
- [X] Feat: QC for UMI: done in PR https://github.com/Clinical-Genomics/BALSAMIC/pull/431
- [X] Feat: quite mode for snakemake: https://github.com/Clinical-Genomics/BALSAMIC/issues/289 . Feature added in https://github.com/Clinical-Genomics/BALSAMIC/pull/438

## Documentation:
- [x] Doc: Snakemake rule standards https://github.com/Clinical-Genomics/BALSAMIC/issues/406 Done in https://github.com/Clinical-Genomics/BALSAMIC/pull/489
- [ ] Doc: BALSAMIC tutorial https://github.com/Clinical-Genomics/BALSAMIC/issues/400
- [ ] Doc: Bioinfo tool description: https://github.com/Clinical-Genomics/BALSAMIC/issues/339

## Fixes:
- [X] Increase memory for VarDict and Mutect2: https://github.com/Clinical-Genomics/BALSAMIC/issues/429 and https://github.com/Clinical-Genomics/BALSAMIC/issues/370 and https://github.com/Clinical-Genomics/BALSAMIC/issues/427 Done in PR: https://github.com/Clinical-Genomics/BALSAMIC/pull/440
- [X] Increase assigned cores for CNVKit https://github.com/Clinical-Genomics/BALSAMIC/issues/476 Done in PR https://github.com/Clinical-Genomics/BALSAMIC/pull/482
- [X] Fixed a bug to not run UMI quality trim for WGS applications https://github.com/Clinical-Genomics/BALSAMIC/issues/473  done in PR https://github.com/Clinical-Genomics/BALSAMIC/pull/486 

## Refactor:
- [x] Refactor: Merge `run reference` and `config reference` done in PR https://github.com/Clinical-Genomics/BALSAMIC/pull/438
- [X] Refactor: Align rules done in PR https://github.com/Clinical-Genomics/BALSAMIC/pull/434
- [X] Refactor: Disable any variant caller done in PR https://github.com/Clinical-Genomics/BALSAMIC/pull/433
- [X] Refactor: fix params to global constants and cleanup of UMI rule names: https://github.com/Clinical-Genomics/BALSAMIC/issues/431
- [X] Refactor: changed wildcard `{sample}` -> `{case_name}` in UMI workflow. Uses vep.somatic rule from balsamic workflow. Done in #514 

## New features:
- [X] Feat: disable/enable variant callers: https://github.com/Clinical-Genomics/BALSAMIC/issues/411 done in https://github.com/Clinical-Genomics/BALSAMIC/pull/417
- [x] Feat: Reference hg38: https://github.com/Clinical-Genomics/BALSAMIC/issues/301 done in https://github.com/Clinical-Genomics/BALSAMIC/pull/407

## Fixes:
- [x] Fix: cyvcf2 and cython missing package https://github.com/Clinical-Genomics/BALSAMIC/issues/409 done in https://github.com/Clinical-Genomics/BALSAMIC/pull/413

#### Added
* UMI workflow using Sentieon tools. Analysis run available via `balsamic run analysis --help` command. PR #359
* VCFutils to create VCF from flat text file. This is for internal purpose to generate validation VCF. PR #349
* Download option for hg38 (not validated) PR #407
* Option to disable variant callers for WES runs. PR #417

#### Fixed
* Missing cyvcf2 dependency, and changed conda environment for base environment PR #413
* Missing numpy dependency PR #426

#### Changed
* COSMIC db for hg19 updated to v90 PR #407
* Fastp trimming is now a two-pass trimming and adapter trimming is always enabled. This might affect coverage slightly PR #422
* All containers start with a clean environment #425
* All Sentieon environment variables are now added to config when workflow executes #425
* Branching model will be changed to gitflow

### Features (new):

- [ ] Feat: Check tumor samples coming from same individual: https://github.com/Clinical-Genomics/BALSAMIC/issues/300
- [x] Feat: Somatic variant caller filters: https://github.com/Clinical-Genomics/BALSAMIC/issues/117
- [ ] Feat: Annotate VCF from other sources than provided by VEP: https://github.com/Clinical-Genomics/BALSAMIC/issues/382
- [ ] Feat: Add tests to Docker container: https://github.com/Clinical-Genomics/BALSAMIC/issues/299
- [ ] Feat: Custom annotation: https://github.com/Clinical-Genomics/BALSAMIC/issues/285
- [ ] Feat: Roh call and LoH: https://github.com/Clinical-Genomics/BALSAMIC/issues/277
- [ ] Feat: GFFToolkits: https://github.com/Clinical-Genomics/BALSAMIC/issues/113
- [ ] Feat: Variant normalization: https://github.com/Clinical-Genomics/BALSAMIC/issues/108
- [ ] Feat: TMB calculation https://github.com/Clinical-Genomics/BALSAMIC/issues/104 and https://github.com/Clinical-Genomics/BALSAMIC/issues/51
- [ ] Feat: Fusioncatcher https://github.com/Clinical-Genomics/BALSAMIC/issues/102
- [ ] Feat: Tumor purity for WGS: https://github.com/Clinical-Genomics/BALSAMIC/issues/101
- [ ] Feat: Tumor purity and clones: https://github.com/Clinical-Genomics/BALSAMIC/issues/100
- [ ] Feat: Ti/Tv report and VCF statistics: https://github.com/Clinical-Genomics/BALSAMIC/issues/93
- [ ] Feat: panel of normals for Mutect2: https://github.com/Clinical-Genomics/BALSAMIC/issues/90
- [ ] Feat: Second aligner for noise suppression: https://github.com/Clinical-Genomics/BALSAMIC/issues/89
- [ ] Feat: Downsample options: https://github.com/Clinical-Genomics/BALSAMIC/issues/84
- [ ] Feat: Plot functionality for coverage: https://github.com/Clinical-Genomics/BALSAMIC/issues/75
- [ ] Feat: Selected SV visualization or Circos visualization: https://github.com/Clinical-Genomics/BALSAMIC/issues/55
- [ ] Feat: observed vs expected plots: https://github.com/Clinical-Genomics/BALSAMIC/issues/25

### Fixes and refactors:
- [ ] Refactor: filter string distribution for variant callers https://github.com/Clinical-Genomics/BALSAMIC/issues/146
- [x] Refactor: tmp_dir workflow wide https://github.com/Clinical-Genomics/BALSAMIC/issues/397
- [x] Refactor: use Python pathlib: https://github.com/Clinical-Genomics/BALSAMIC/issues/377
- [x] Refactor: decouple environments from single container: https://github.com/Clinical-Genomics/BALSAMIC/issues/326
- [x] Refactor: sample names in merged bam files: https://github.com/Clinical-Genomics/BALSAMIC/issues/243
- [x] Refactor: improve run time for Strelka: https://github.com/Clinical-Genomics/BALSAMIC/issues/118

**Comment by hassanfa** [comment]
This is mostly done. Will create a new one for 2021.
